### ISSUE TITLE
kb grep "IndexError: list index out of range"

### ISSUE THREAD

**Issue by ArchWizard56** [gnebbia/kb#83] opened 2021-03-30 17:44 UTC
Hi! It's me again. I've been working on migrating my notes into kb, and I ran across this error. I'm planning on looking into it a bit, but I wanted to open the issue first.

## Expected Behavior
kb ought to display a list of artifacts containing the word, as shown in https://github.com/gnebbia/kb#grep-through-the-knowledge-base

## Actual Behavior
kb throws an IndexError. This only seems to occur if the grep successfully matches an artifact. Nothing seems to change if I use the -v flag. It works if I use the -m flag to show the matching lines instead of the artifacts.

Ghostbin with full error: https://ghostbin.co/paste/tyqqos

## Steps to Reproduce the Problem

  1. Run `kb grep` with any word that exists in the knowledge base.

## Specifications

  - Version: kb-git from the AUR.
  - Platform: Arch Linux

**Comment by gnebbia** [comment] 2021-03-30 20:50
Dear Sir, I am unable to reproduce the error, can we try to isolate the issue by being more specific about when this throws an exception?

**Comment by hexiyou** [comment] 2021-05-10 12:02
I had the same problem on Cygwin：
![image](https://user-images.githubusercontent.com/1593944/117656082-7cc92800-b1ca-11eb-8de0-5f8e9b2adc40.png)

**Comment by gnebbia** [comment] 2021-05-10 15:29
Dear Sir, this looks a lot like an older version bug, could you try to uninstall kb and try to re-install the latest version?
Thanks a lot

**Comment by gnebbia** [comment] 2021-05-11 18:29
Can you let me know if the bug persists on the latest version?

**Comment by hexiyou** [comment] 2021-05-12 17:09
> Can you let me know if the bug persists on the latest version?

I already uninstall local version and reinstall from github repository，then i got the same problem.

![image](https://user-images.githubusercontent.com/1593944/118016215-b98e4e00-b387-11eb-9888-f078b81bbd97.png)

---

![image](https://user-images.githubusercontent.com/1593944/118016357-dfb3ee00-b387-11eb-9b63-284306b4e77a.png)

**Comment by gnebbia** [comment] 2021-05-12 17:13
How can i reproduce this? Could you send me some articles from your knowledge base? so that I can inspect them? Probaby related to some UTF-8 char? Did you try deleting your knowledge base and trying to import it again?

You can do something like:
kb add ./myelectornicsstuff/*                --category "electronics"
kb add ./cheatsheet/*                   --category "cheatsheet"
kb add ./protocol/*                     --category "protocol"
kb add ./config/*                       --category "config"

To quickly reimport your artcles from text files.
Could you do that test for me?
Because I am not able to reproduce the issue.
Thanks a lot!

**Comment by gnebbia** [comment] 2021-05-15 17:30
> > Can you let me know if the bug persists on the latest version?
> 
> I already uninstall local version and reinstall from github repository，then i got the same problem.
> 
> ![image](https://user-images.githubusercontent.com/1593944/118016215-b98e4e00-b387-11eb-9888-f078b81bbd97.png)
> 
> ![image](https://user-images.githubusercontent.com/1593944/118016357-dfb3ee00-b387-11eb-9b63-284306b4e77a.png)

Ok, I think I was able to track the issue. I think that updating kb was not enough since this is related to how kb used to store in previous versions artifacts.

Hence, I htink you should basically delete your knowledge base and re-import it.

Unluckily these were issues of previous versions of kb on how data was stored. These issues are fixed with the latest version.

**Comment by prokaryont** [comment] 2021-06-19 17:06
Hi,

i found that the problem (also?) occurs when the title of an artifact contains spaces. Reproducing the error:
```bash
kb add -t 'win style name' -b win
kb grep win
```

![01_space_title_error](https://user-images.githubusercontent.com/4510525/122649729-89c52980-d12f-11eb-8a29-e5398e6289d9.png)

The cause seems that [get_filename_parts_wo_prefix()](https://github.com/gnebbia/kb/blob/6a1e060dbd8cb0152950ae3f130c35a444c3cd2c/kb/filesystem.py#L240) parses the title of the artifacts incorrectly.

![02_incorrectly_parsed_title](https://user-images.githubusercontent.com/4510525/122649765-cee95b80-d12f-11eb-8fe4-b1928ad652a5.png)

Instead of the expected two element tuple of the form `[(category, title)]`, the returned list contains a tuple `('default', 'win', 'style', 'name')`. Later, when results are fetches with [db_get_artifacts_by_filter()](https://github.com/gnebbia/kb/blob/6a1e060dbd8cb0152950ae3f130c35a444c3cd2c/kb/commands/grep.py#L80), the category parameter is `default/win/style`. The call returns an empty list and when the result is indexed the IndexError is raised.

![04_incorrect_category_parameter](https://user-images.githubusercontent.com/4510525/122649847-3dc6b480-d130-11eb-8a77-ab1a5fc06e52.png)

**Quick fix for the users** until the issue is resolved: remove spaces/backslashes from your artifacts' titles.

For parsing the path correctly, the [pathlib](https://docs.python.org/3/library/pathlib.html#module-pathlib) module might help. I'm not sure why backslashes are removed. Is this done to ensure windows compatibility?

**Closed** 2021-06-21 07:10 UTC
